blank_issues_enabled: false
contact_links:
  - name: Some issue with your console after/during following the guide?
    url: https://discord.gg/MWxPgEp
    about: "Please join the Nintendo Homebrew Discord server to for support-related questions"
